# Generated by Django 3.0.8 on 2020-07-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketOrders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(blank=True, max_length=128, null=True)),
                ('location', models.PositiveSmallIntegerField()),
                ('quality_level', models.PositiveIntegerField()),
                ('enchantment_level', models.PositiveIntegerField()),
                ('price', models.BigIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('auction_type', models.CharField(blank=True, max_length=32, null=True)),
                ('expires', models.DateTimeField()),
                ('albion_id', models.BigIntegerField(unique=True)),
                ('initial_amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'market_orders',
            },
        ),
        migrations.CreateModel(
            name='MarketStats',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=128)),
                ('location', models.PositiveSmallIntegerField()),
                ('price_avg', models.DecimalField(decimal_places=30, max_digits=65)),
                ('price_max', models.BigIntegerField()),
                ('price_min', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'market_stats',
                'unique_together': {('item_id', 'location', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='MarketHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_amount', models.BigIntegerField()),
                ('silver_amount', models.BigIntegerField()),
                ('item_id', models.CharField(max_length=128)),
                ('location', models.PositiveSmallIntegerField()),
                ('quality', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('aggregation', models.IntegerField()),
            ],
            options={
                'db_table': 'market_history',
                'unique_together': {('item_id', 'quality', 'location', 'timestamp', 'aggregation')},
            },
        ),
    ]
