# Generated by Django 3.0.8 on 2020-08-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200826_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='key',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='requests',
            name='auth_key',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='requests',
            name='ip',
            field=models.TextField(max_length=46),
        ),
        migrations.AlterField(
            model_name='requests',
            name='user_agent',
            field=models.TextField(max_length=200),
        ),
    ]
