# Generated by Django 3.1.1 on 2021-03-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20200827_0007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keys',
        ),
        migrations.DeleteModel(
            name='Requests',
        ),
    ]
